services:
  Vincit\VersioningApi\Bundle\Controller\Rest\VersioningApiController:
    public: true
    class: 'Vincit\VersioningApi\Bundle\Controller\Rest\VersioningApiController'
    arguments:
      - '@security.token_storage'
      - '@oro_security.security_facade'
      - '@logger'
      - '@pim_versioning.repository.version'
      - '@database_connection'
    calls:
      - [ 'setContainer', [ '@service_container' ] ]
    tags:
      - { name: controller.service_arguments }

  versioning.api.rest.controller:
    alias: Vincit\VersioningApi\Bundle\Controller\Rest\VersioningApiController
    public: true
